export const data = [
    {
        nama_pasangan: "Romeo & Juliet",
        nama_panggilan_cowo: "Romeo",
        nama_panggilan_cewe: "Juliet",
        nama_lengkap_cowo: "Romeo Ramadhan",
        nama_lengkap_cewe: "Juliet Ramadhini",
        nama_ortu_cowo: "Putra Pertama Bapak Roma & Ibu Saputri",
        nama_ortu_cewe: "Putri Pertama Bapak Juli & Ibu putri",
        tgl_akad: "11 November 2025",
        jam_akad: "10:00",
        alamat_akad: "Ds Konohagakure Kec. Konoha Kab. Negara Api",
        tgl_resepsi: "11 November 2025",
        jam_resepsi: "12:00",
        alamat_resepsi: "Ds Konohagakure Kec. Konoha Kab. Negara Api",
        no_amplop_bri: "42424242",
        atas_nama_bri: "Romeo Ramadhan",
        no_amplop_shpe: "085742068498",
        atas_nama_shpe: "Romeo Ramadhan",
        btn_kalender: "https://calendar.google.com/event?action=TEMPLATE&tmeid=M3JxODhvNGlhZTVqbW1tOGY2NW5qb2RlZTUgeWFyZWFwazI0QG0&tmsrc=yareapk24%40gmail.com",
        btn_fb_cewe: "https://instagram.com/artyardhan?utm_medium=copy_link",
        btn_ig_cewe: "https://instagram.com/artyardhan?utm_medium=copy_link",
        btn_fb_cowo: "https://instagram.com/artyardhan?utm_medium=copy_link",
        btn_ig_cowo: "https://instagram.com/artyardhan?utm_medium=copy_link",
        btn_gmaps: "https://goo.gl/maps/AteGNbZYT6zuuXn5A",
        btn_live_ig: "https://instagram.com/artyardhan?utm_medium=copy_link",
        btn_live_yt: "https://youtube.com/channel/UCtJ9lY89-ZTYR9RNBhpLH6g",
    }
]
